DROP TABLE IF EXISTS TodoListItem;

CREATE TABLE IF NOT EXISTS TodoListItem (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	checked INTEGER DEFAULT FALSE,
	created_at TEXT DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
