DROP TABLE IF EXISTS TodoListItem;

DROP TABLE IF EXISTS User;

CREATE TABLE IF NOT EXISTS TodoListItem (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	checked INTEGER DEFAULT FALSE,
	createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
	updatedAt TEXT DEFAULT CURRENT_TIMESTAMP
) STRICT;

CREATE TABLE IF NOT EXISTS User (
	id INTEGER PRIMARY KEY,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
	updatedAt TEXT DEFAULT CURRENT_TIMESTAMP
) STRICT;
