DROP TABLE IF EXISTS TodoListItem;

CREATE TABLE IF NOT EXISTS TodoListItem (
	id BIGINT PRIMARY KEY,
	name TEXT NOT NULL,
	checked INTEGER DEFAULT FALSE,
	created_at INTEGER DEFAULT CURRENT_TIMESTAMP,
	updated_at INTEGER DEFAULT CURRENT_TIMESTAMP
);
